WebApplication1/Controllers/GigsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Dynamic;

namespace WebApplication1.Controllers
{
    public class GigsController : Controller
    {
        public Gig cgig = new Gig();
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Gigs
        protected string CurrentUserID
        {
            get
            {
                return System.Web.HttpContext.Current.GetOwinContext()
                      .GetUserManager<ApplicationUserManager>()
                      .FindById(System.Web.HttpContext.Current.User.Identity.GetUserId()).Id;
            }
        }
        [Authorize(Roles = "Admin,Seller,Buyer")]
        public ActionResult Index(string id)
        {
            if (id != null)
            {
                return View(db.Gigs.Where(g => g.Seller.Id == id).ToList());
            }
            return View(db.Gigs.ToList());
        }

        [Authorize(Roles = "Admin,Seller")]
        public ActionResult MyGigs()
        {
            return View(db.Gigs.Where(g => g.Seller.Id == CurrentUserID).ToList());
        }

        //[Authorize(Roles = "Admin,Seller,Buyer")]
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gig gig = db.Gigs.Find(id);
            cgig = gig;
            ViewBag.GigID = id;
            if (gig == null)
            {
                return HttpNotFound();
            }

            return View(gig);
        }


        [Authorize(Roles = "Admin,Seller,Buyer")]
        public ActionResult Create()
        {
            return View();
        }

        //[Authorize(Roles = "Admin,Seller,Buyer")]
        public ActionResult PlaceAnOrder(int? id)
        {
            Order neworder = new Order();
            Gig cgig = db.Gigs.SingleOrDefault(g => g.GigID == 4);
            neworder.Buyer = db.Users.SingleOrDefault(e => e.Id == CurrentUserID);
            neworder.Gig = cgig;
            neworder.Amount = 1;
            neworder.OrderDate = DateTime.Now;
            neworder.Status = 1;
            db.Orders.Add(neworder);
            db.SaveChanges();
            return RedirectToAction("MyOrders", "Orders");
        }
        /*
        //[Authorize(Roles = "Admin,Seller,Buyer")]
        [HttpPost]
        public ActionResult PlaceAnOrder([Bind(Include = "OrderID,Amount,OrderDate,Status,Buyer,Gig")] Order order)
        {
            ViewBag.GigID = cgig.GigID;
            if (ModelState.IsValid)
            {
                order.Buyer = db.Users.SingleOrDefault(e => e.Id == CurrentUserID);
                order.Gig = cgig;
                order.OrderDate = DateTime.Now;
                order.Status = 1;
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("MyOrders","Orders");
            }

            return View(order);
        }
        */
        [Authorize(Roles = "Admin,Seller,Buyer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GigID,Name,Description,Price,Deliverytime,Seller")] Gig gig)
        {
            if (ModelState.IsValid)
            {
                gig.Seller = db.Users.SingleOrDefault(e => e.Id == CurrentUserID);
                System.Web.HttpContext.Current.GetOwinContext()
                      .GetUserManager<ApplicationUserManager>().AddToRole(CurrentUserID,"Seller");
                db.Gigs.Add(gig);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gig);
        }
        // GET: Gigs/Edit/5
        [Authorize(Roles = "Admin,Seller")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gig gig = db.Gigs.Find(id);
            if (gig == null)
            {
                return HttpNotFound();
            }
            return View(gig);
        }

        [Authorize(Roles = "Admin,Seller")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GigID,Name,Description,Price,Deliverytime")] Gig gig)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gig).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gig);
        }

        [Authorize(Roles = "Admin,Seller")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gig gig = db.Gigs.Find(id);
            if (gig == null)
            {
                return HttpNotFound();
            }
            return View(gig);
        }

        [Authorize(Roles = "Admin,Seller")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gig gig = db.Gigs.Find(id);
            db.Gigs.Remove(gig);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Gigs/Create.cshtml
@model WebApplication1.Models.Gig

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gig</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Deliverytime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Deliverytime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Deliverytime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Gigs/Delete.cshtml
@model WebApplication1.Models.Gig

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Gig</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deliverytime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deliverytime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Gigs/Details.cshtml
@model WebApplication1.Models.Gig

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Gig</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deliverytime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deliverytime)
        </dd>
        @Model.GigID - @ViewBag.GigID
    </dl>
</div>
<p>
@Html.ActionLink("Place an order","PlaceAnOrder","Gigs", new { id = ViewBag.GigID, gig = ViewBag.GigID })
@Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/Gigs/Edit.cshtml
@model WebApplication1.Models.Gig

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gig</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GigID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Deliverytime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Deliverytime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Deliverytime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Gigs/Index.cshtml
@model IEnumerable<WebApplication1.Models.Gig>

@{
    ViewBag.Title = "Gigs";
}

<h2>Gigs</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Deliverytime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Deliverytime)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.GigID })
        </td>
    </tr>
}

</table>

WebApplication1/Views/Gigs/MyGigs.cshtml
@model IEnumerable<WebApplication1.Models.Gig>

@{
    ViewBag.Title = "My gigs";
}

<h2>My gigs</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Deliverytime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Deliverytime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.GigID }) |
            @Html.ActionLink("Details", "Details", new { id=item.GigID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.GigID })
        </td>
    </tr>
}

</table>

WebApplication1/Views/Gigs/PlaceAnOrder.cshtml
@model WebApplication1.Models.Order

@{
    ViewBag.Title = "Place an order";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Gig, new { id = "Gig", Value = ViewBag.Gig })
                @ViewBag.Gig - @ViewBag.Ajdi - @ViewBag.GigID

                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}